### ISSUE TITLE
WWF No Mercy texture issues with Intro

### ISSUE THREAD

**Issue by weinerschnitzel** [death-droid/Rice-Video#11]
This issue is a regression from Rice 5.60

![wwf_nomercy_intro1](https://cloud.githubusercontent.com/assets/5079789/7288979/d3144eb0-e926-11e4-9f4b-fbb06d0ede5d.jpg)
![wwf_nomercy_intro2](https://cloud.githubusercontent.com/assets/5079789/7288981/d53632c6-e926-11e4-8165-467ac8a0804d.jpg)

**Comment by death-droid** [comment]
Ouch thats quite a nasty bug there. Will definitely look into it at some point

**Comment by LegendOfDragoon** [comment]
This regression seems to be from before the first commit in this repo. You'll have to test out commits from the 1964 Video repo. I didn't see this issue in Rice Video 6.1.0.

**Comment by weinerschnitzel** [comment]
https://github.com/death-droid/Rice-Video/blob/a3b24c65f6ab8a0bea43bb043b404a7175b00532/Render/RenderBase.cpp#L715-L716

```
uint16 x = (uint16)(val >> 16) >> 2;
uint16` y = (uint16)(val & 0xFFFF) >> 2;
```
should be:

```
uint16 nX = (uint16)(val>>16);
short x = *((short*)&nX);
x /= 4;

uint16 nY = uint16(val&0xFFFF);
short y = *((short*)&nY);
y /= 4;
```

**Comment by death-droid** [comment]
Cheers mate! Your doing a superb job at finding all these regressions.
