### ISSUE TITLE
Top Gear Overdrive gfx issues

### ISSUE THREAD

**Issue by weinerschnitzel** [death-droid/Rice-Video#14]
Top Gear Overdrive's gfx are broken. I believe it is related to the the matter with TGR as discussed by Narann here: http://www.emutalk.net/threads/55135-Rice-to-OpenGL-2-1-%28and-potentially-ES%29?p=453552&viewfull=1#post453552

Readding the old hack from DecodedMux should fix this.

![tgo](https://cloud.githubusercontent.com/assets/5079789/7321216/32b8c728-ea5e-11e4-9c2e-c2fc6c9d626d.jpg)

This issue is separate from #13

**Comment by exhalatio** [comment]
It seems when you enable the option Alternative texture size calculation to fix.

**Comment by death-droid** [comment]
Interesting, I'm still trying to work out how exactly all the texture code works, the TMEM code itself seems like a mess, but undoing that mess seems to be a big project in itself

**Comment by weinerschnitzel** [comment]
https://github.com/death-droid/Rice-Video/blob/master/Parser/RDP_Texture.h#L526-L536

should be:

```
		loadwidth = abs(tile.sh - tile.sl) +1;
		if( tile.dwMaskS )	
		{
			if( !tile.bSizeIsValid )	
				loadwidth = maskwidth;
			else
				loadwidth = min(loadwidth, maskwidth);
		}

		loadheight = abs(tile.th - tile.tl) +1;
		if( tile.dwMaskT )	
		{
			if( !tile.bSizeIsValid )	
				loadheight = maskheight;
			else
				loadheight = min(loadheight, maskheight);
		}
```
Taken from 1964video 1.0.0.

**Comment by death-droid** [comment]
@weinerschnitzel thanks a heap for finding that mate!
