### ISSUE TITLE
MK64 graphics mess

### ISSUE THREAD

**Issue by jfields687** [death-droid/Rice-Video#15]
Something in the 12-02-2014 release has messed up MK64 in 2 player mode or more. The 12-01-2014 release does not have this problem.
![mk64 mess](https://cloud.githubusercontent.com/assets/12734891/8193476/087b7dca-1443-11e5-8677-02efb8dad4f5.png)

**Comment by death-droid** [comment]
Thanks for the issue report, would of never picked it up otherwise. Looking into the exact commit where it stops working! Cheers

**Comment by jfields687** [comment]
One of these is the culprit

RiceVideo Git Changelog (2014/12/02):
* [~] Really need to spend alot of time with the framebuffer :\ still not sure if its worth trying to salvage whats here, it seems a complete mess to me
* [~]Annoying behavior, most people wont want to bother with the per rom setting.
* [-]Strip out alot of now pointless hacks, or hacks that should be removed to be able to fix underlying problems
[~]Fix up comboboxes not displaying correctly.

**Comment by jfields687** [comment]
Thanks very much!! :D
