### ISSUE TITLE
Build in x64

### ISSUE THREAD

**Issue by tony971** [death-droid/Rice-Video#19]
PJ64 builds in x64 now and so does AziAudio and the N-Rage plugin. The RSP recompiler doesn't work, but HatCat's RSP does. I've heard that [this fork](https://github.com/r52/Rice-Video) builds in x64 but it uses some depreciated functions that don't work with VS15.

**Comment by death-droid** [comment]
It shouldn't take much to get Rice Video to compile in 64 bit. I'll take a look in a little while. Just got to get the directx sdk to actually install again. Had to wipe my computer yet again :\

**Comment by DaMan69** [comment]
[This guy already did the work](https://github.com/r52/Rice-Video).

**Comment by death-droid** [comment]
Code does not operate correctly.

**Comment by death-droid** [comment]
Use latest commit.

**Comment by tony971** [comment]
it builds :) thanks!
